export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lightblue", padding: "1rem"}} >
          <p>Header</p>
        </header>
        {children} 
        {/* children prop get replaces by component defined in page.tsx */}
        <footer style={{backgroundColor: "grey", padding: "1rem"}} >
          <p>Footer</p>
          </footer>
      </body>
    </html>
  )
}
